CREATE TABLE "role"(
	"id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name" VARCHAR(64) NOT NULL
);

CREATE TABLE "app_key"(
	"id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"role_id" INTEGER NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"key" VARCHAR(255) NOT NULL,
	"identity" VARCHAR(255) NOT NULL,
	"created_date" DATETIME NOT NULL,
    FOREIGN KEY("role_id") REFERENCES "role" ("id"),
    UNIQUE("name")
);

INSERT INTO "role"("name") VALUES ("manager");
