/*
 * Golem Market API
 *
 * Market API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct PropertyQueryResponse {}

impl PropertyQueryResponse {
    pub fn new() -> PropertyQueryResponse {
        PropertyQueryResponse {}
    }
}
