/*
 * Golem Market API
 *
 * Market API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct ProviderEvent {
    #[serde(rename = "eventType")]
    event_type: String,
    #[serde(rename = "requestorId")]
    requestor_id: String,
}

impl ProviderEvent {
    pub fn new(event_type: String, requestor_id: String) -> ProviderEvent {
        ProviderEvent {
            event_type: event_type,
            requestor_id: requestor_id,
        }
    }

    pub fn set_event_type(&mut self, event_type: String) {
        self.event_type = event_type;
    }

    pub fn with_event_type(mut self, event_type: String) -> ProviderEvent {
        self.event_type = event_type;
        self
    }

    pub fn event_type(&self) -> &String {
        &self.event_type
    }

    pub fn set_requestor_id(&mut self, requestor_id: String) {
        self.requestor_id = requestor_id;
    }

    pub fn with_requestor_id(mut self, requestor_id: String) -> ProviderEvent {
        self.requestor_id = requestor_id;
        self
    }

    pub fn requestor_id(&self) -> &String {
        &self.requestor_id
    }
}
