use std::sync::Arc;

use super::super::callbacks::{CallbackHandler, HandlerSlot};
use super::errors::{AgreementError, CounterProposalError, NegotiationApiInitError, ProposalError};
use super::messages::*;
use super::messages::{AgreementApproved, AgreementRejected, ProposalReceived, ProposalRejected};

use crate::db::models::Proposal;

use ya_client::model::NodeId;
use ya_core_model::market::BUS_ID;
use ya_net::{self as net, RemoteEndpoint};
use ya_service_bus::typed::ServiceBinder;
use ya_service_bus::RpcEndpoint;

/// Responsible for communication with markets on other nodes
/// during negotiation phase.
#[derive(Clone)]
pub struct NegotiationApi {
    inner: Arc<NegotiationImpl>,
}

struct NegotiationImpl {
    proposal_received: HandlerSlot<ProposalReceived>,
    proposal_rejected: HandlerSlot<ProposalRejected>,
    agreement_approved: HandlerSlot<AgreementApproved>,
    agreement_rejected: HandlerSlot<AgreementRejected>,
}

impl NegotiationApi {
    pub fn new(
        proposal_received: impl CallbackHandler<ProposalReceived>,
        proposal_rejected: impl CallbackHandler<ProposalRejected>,
        agreement_approved: impl CallbackHandler<AgreementApproved>,
        agreement_rejected: impl CallbackHandler<AgreementRejected>,
    ) -> NegotiationApi {
        let negotiation_impl = NegotiationImpl {
            proposal_received: HandlerSlot::new(proposal_received),
            proposal_rejected: HandlerSlot::new(proposal_rejected),
            agreement_approved: HandlerSlot::new(agreement_approved),
            agreement_rejected: HandlerSlot::new(agreement_rejected),
        };
        NegotiationApi {
            inner: Arc::new(negotiation_impl),
        }
    }

    /// Sent to provider, when Requestor counters initial proposal
    /// generated by market.
    pub async fn initial_proposal(&self, proposal: Proposal) -> Result<(), CounterProposalError> {
        log::debug!(
            "Sending initial proposal [{}] to [{}].",
            proposal.body.id.clone(),
            proposal.negotiation.provider_id
        );

        let content = ProposalContent::from(proposal.body);
        let msg = InitialProposalReceived {
            proposal: content,
            offer_id: proposal.negotiation.offer_id,
            demand_id: proposal.negotiation.demand_id,
        };
        net::from(proposal.negotiation.requestor_id)
            .to(proposal.negotiation.provider_id)
            .service(&provider::proposal_addr(BUS_ID))
            .send(msg)
            .await??;
        Ok(())
    }

    /// Counter proposals used in all other cases, when proposal
    /// is not in initial state.
    pub async fn counter_proposal(&self, proposal: Proposal) -> Result<(), CounterProposalError> {
        log::debug!(
            "Counter proposal [{}] sent by [{}].",
            proposal.body.id.clone(),
            proposal.negotiation.provider_id
        );

        let prev_proposal_id = proposal.body.prev_proposal_id.clone();
        if prev_proposal_id.is_none() {
            Err(CounterProposalError::NoPreviousProposal(
                proposal.body.id.clone(),
            ))?
        }

        let content = ProposalContent::from(proposal.body);
        let msg = ProposalReceived {
            proposal: content,
            prev_proposal_id: prev_proposal_id.unwrap(),
        };
        net::from(proposal.negotiation.requestor_id)
            .to(proposal.negotiation.provider_id)
            .service(&provider::proposal_addr(BUS_ID))
            .send(msg)
            .await??;
        Ok(())
    }

    // TODO: Use model Proposal struct.
    pub async fn reject_proposal(
        &self,
        id: NodeId,
        proposal_id: &str,
        owner: NodeId,
    ) -> Result<(), ProposalError> {
        let msg = ProposalRejected {
            proposal_id: proposal_id.to_string(),
        };
        net::from(id)
            .to(owner)
            .service(&provider::proposal_addr(BUS_ID))
            .send(msg)
            .await??;
        Ok(())
    }

    /// Sent to provider, when Requestor will call confirm Agreement.
    /// TODO: send Agreement content
    pub async fn propose_agreement(
        &self,
        id: NodeId,
        agreement_id: &str,
        owner: NodeId,
    ) -> Result<(), AgreementError> {
        let msg = AgreementReceived {
            agreement_id: agreement_id.to_string(),
        };
        net::from(id)
            .to(owner)
            .service(&provider::agreement_addr(BUS_ID))
            .send(msg)
            .await??;
        Ok(())
    }

    /// Sent to provider, when Requestor will call cancel Agreement,
    /// while waiting for approval.
    /// TODO: Use model Agreement struct in api.
    pub async fn cancel_agreement(
        &self,
        id: NodeId,
        agreement_id: &str,
        owner: NodeId,
    ) -> Result<(), AgreementError> {
        let msg = AgreementCancelled {
            agreement_id: agreement_id.to_string(),
        };
        net::from(id)
            .to(owner)
            .service(&provider::agreement_addr(BUS_ID))
            .send(msg)
            .await??;
        Ok(())
    }

    async fn on_proposal_received(
        self,
        caller: String,
        msg: ProposalReceived,
    ) -> Result<(), CounterProposalError> {
        log::debug!(
            "Negotiation API: Received proposal [{}] from [{}].",
            &msg.proposal.proposal_id,
            &caller
        );
        self.inner.proposal_received.call(caller, msg).await
    }

    async fn on_proposal_rejected(
        self,
        caller: String,
        msg: ProposalRejected,
    ) -> Result<(), ProposalError> {
        log::debug!(
            "Negotiation API: Proposal [{}] rejected by [{}].",
            &msg.proposal_id,
            &caller
        );
        self.inner.proposal_rejected.call(caller, msg).await
    }

    async fn on_agreement_approved(
        self,
        caller: String,
        msg: AgreementApproved,
    ) -> Result<(), AgreementError> {
        log::debug!(
            "Negotiation API: Agreement [{}] approved by [{}].",
            &msg.agreement_id,
            &caller
        );
        self.inner.agreement_approved.call(caller, msg).await
    }

    async fn on_agreement_rejected(
        self,
        caller: String,
        msg: AgreementRejected,
    ) -> Result<(), AgreementError> {
        log::debug!(
            "Negotiation API: Agreement [{}] rejected by [{}].",
            &msg.agreement_id,
            &caller
        );
        self.inner.agreement_rejected.call(caller, msg).await
    }

    pub async fn bind_gsb(
        &self,
        public_prefix: &str,
        private_prefix: &str,
    ) -> Result<(), NegotiationApiInitError> {
        ServiceBinder::new(&requestor::proposal_addr(public_prefix), &(), self.clone())
            .bind_with_processor(move |_, myself, caller: String, msg: ProposalReceived| {
                let myself = myself.clone();
                myself.on_proposal_received(caller, msg)
            })
            .bind_with_processor(move |_, myself, caller: String, msg: ProposalRejected| {
                let myself = myself.clone();
                myself.on_proposal_rejected(caller, msg)
            });

        ServiceBinder::new(&requestor::agreement_addr(public_prefix), &(), self.clone())
            .bind_with_processor(move |_, myself, caller: String, msg: AgreementApproved| {
                let myself = myself.clone();
                myself.on_agreement_approved(caller, msg)
            })
            .bind_with_processor(move |_, myself, caller: String, msg: AgreementRejected| {
                let myself = myself.clone();
                myself.on_agreement_rejected(caller, msg)
            });
        Ok(())
    }
}
