#!/bin/sh

[ "$1" = "install" ] || return 0

. /usr/share/debconf/confmodule

db_version 2.0
db_input critical golem/terms/testnet-01
db_go

db_get golem/terms/testnet-01 || true

if [ "$RET" != "yes" ]; then
    db_input critical golem/tos-rejected
    db_go
    db_reset golem/terms/testnet-01
    exit 1
fi


