/*
 * Yagna Activity API
 *
 * It conforms with capability level 1 of the [Activity API specification](https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM).
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExeScriptCommand {
    #[serde(rename = "command")]
    pub command: String,
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Vec<String>>,
}

impl ExeScriptCommand {
    pub fn new(command: String) -> ExeScriptCommand {
        ExeScriptCommand {
            command,
            params: None,
        }
    }
}
