/*
 * Yagna Activity API
 *
 * It conforms with capability level 1 of the [Activity API specification](https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM).
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExeScriptRequest {
    #[serde(rename = "text")]
    pub text: String,
}

impl ExeScriptRequest {
    pub fn new(text: String) -> ExeScriptRequest {
        ExeScriptRequest { text }
    }
}
