use futures::future::TryFutureExt;
use std::sync::Arc;

use ya_client::model::market::Reason;
use ya_client::model::NodeId;
use ya_core_model::market::BUS_ID;
use ya_net::{self as net, RemoteEndpoint};
use ya_service_bus::{typed::ServiceBinder, RpcEndpoint};

use crate::db::model::{Agreement, Owner, Proposal};

use super::super::callback::{CallbackHandler, HandlerSlot};
use super::error::{
    AgreementProtocolError, CounterProposalError, GsbAgreementError, GsbProposalError,
    NegotiationApiInitError, TerminateAgreementError,
};
use super::messages::{
    provider, requestor, AgreementApproved, AgreementCancelled, AgreementReceived,
    AgreementRejected, AgreementTerminated, InitialProposalReceived, ProposalContent,
    ProposalReceived, ProposalRejected,
};
use crate::protocol::negotiation::error::{
    CommitAgreementError, ProposeAgreementError, RejectProposalError,
};
use crate::protocol::negotiation::messages::AgreementCommitted;
use chrono::NaiveDateTime;

/// Responsible for communication with markets on other nodes
/// during negotiation phase.
#[derive(Clone)]
pub struct NegotiationApi {
    inner: Arc<NegotiationImpl>,
}

struct NegotiationImpl {
    proposal_received: HandlerSlot<ProposalReceived>,
    proposal_rejected: HandlerSlot<ProposalRejected>,
    agreement_approved: HandlerSlot<AgreementApproved>,
    agreement_rejected: HandlerSlot<AgreementRejected>,
    agreement_terminated: HandlerSlot<AgreementTerminated>,
}

// TODO: Most of these functions don't need to be members of NegotiationApi.
//  We should make them plain functions in `requestor` module, since it doesn't
//  seem, that they will ever need self.
impl NegotiationApi {
    pub fn new(
        proposal_received: impl CallbackHandler<ProposalReceived>,
        proposal_rejected: impl CallbackHandler<ProposalRejected>,
        agreement_approved: impl CallbackHandler<AgreementApproved>,
        agreement_rejected: impl CallbackHandler<AgreementRejected>,
        agreement_terminated: impl CallbackHandler<AgreementTerminated>,
    ) -> NegotiationApi {
        let negotiation_impl = NegotiationImpl {
            proposal_received: HandlerSlot::new(proposal_received),
            proposal_rejected: HandlerSlot::new(proposal_rejected),
            agreement_approved: HandlerSlot::new(agreement_approved),
            agreement_rejected: HandlerSlot::new(agreement_rejected),
            agreement_terminated: HandlerSlot::new(agreement_terminated),
        };
        NegotiationApi {
            inner: Arc::new(negotiation_impl),
        }
    }

    /// Sent to provider, when Requestor counters initial proposal
    /// generated by market.
    pub async fn initial_proposal(&self, proposal: Proposal) -> Result<(), CounterProposalError> {
        let proposal_id = proposal.body.id.clone();
        log::debug!(
            "Sending initial proposal [{}] to [{}].",
            proposal_id,
            proposal.negotiation.provider_id
        );

        let content = ProposalContent::from(proposal.body);
        let msg = InitialProposalReceived {
            proposal: content,
            offer_id: proposal.negotiation.offer_id,
            demand_id: proposal.negotiation.demand_id,
        };
        net::from(proposal.negotiation.requestor_id)
            .to(proposal.negotiation.provider_id)
            .service(&provider::proposal_addr(BUS_ID))
            .send(msg)
            .await
            .map_err(|e| GsbProposalError(e.to_string(), proposal_id))??;
        Ok(())
    }

    /// Counter proposals used in all other cases, when proposal
    /// is not in initial state.
    pub async fn counter_proposal(&self, proposal: Proposal) -> Result<(), CounterProposalError> {
        let proposal_id = proposal.body.id.clone();
        log::debug!(
            "Counter proposal [{}] sent by [{}].",
            proposal_id,
            proposal.negotiation.provider_id
        );

        let prev_proposal_id = proposal.body.prev_proposal_id.clone();
        if prev_proposal_id.is_none() {
            Err(CounterProposalError::NoPrevious(proposal.body.id.clone()))?
        }

        let content = ProposalContent::from(proposal.body);
        let msg = ProposalReceived {
            proposal: content,
            prev_proposal_id: prev_proposal_id.unwrap(),
        };
        net::from(proposal.negotiation.requestor_id)
            .to(proposal.negotiation.provider_id)
            .service(&provider::proposal_addr(BUS_ID))
            .send(msg)
            .await
            .map_err(|e| GsbProposalError(e.to_string(), proposal_id))??;
        Ok(())
    }

    pub async fn reject_proposal(
        &self,
        id: NodeId,
        proposal: &Proposal,
        reason: Option<Reason>,
    ) -> Result<(), RejectProposalError> {
        net::from(id)
            .to(proposal.negotiation.provider_id)
            .service(&provider::proposal_addr(BUS_ID))
            .send(ProposalRejected::of(proposal, reason))
            .await
            .map_err(|e| GsbProposalError(e.to_string(), proposal.body.id.clone()))??;
        Ok(())
    }

    /// Sent to provider, when Requestor will call confirm Agreement.
    pub async fn propose_agreement(
        &self,
        agreement: &Agreement,
    ) -> Result<(), ProposeAgreementError> {
        let requestor_id = agreement.requestor_id.clone();
        let provider_id = agreement.provider_id.clone();
        let id = agreement.id.clone();
        let msg = AgreementReceived {
            agreement_id: agreement.id.clone(),
            valid_to: agreement.valid_to.clone(),
            creation_ts: agreement.creation_ts.clone(),
            proposal_id: agreement.offer_proposal_id.clone(),
            signature: agreement
                .proposed_signature
                .clone()
                .ok_or_else(|| ProposeAgreementError::NotSigned(id.clone()))?,
        };
        net::from(requestor_id)
            .to(provider_id)
            .service(&provider::agreement_addr(BUS_ID))
            .send(msg)
            .map_err(|e| GsbAgreementError(e.to_string(), id))
            .await??;
        Ok(())
    }

    pub async fn commit_agreement(agreement: &Agreement) -> Result<(), CommitAgreementError> {
        let requestor_id = agreement.requestor_id.clone();
        let provider_id = agreement.provider_id.clone();
        let id = agreement.id.clone();
        let msg = AgreementCommitted {
            agreement_id: agreement.id.clone(),
            signature: agreement
                .committed_signature
                .clone()
                .ok_or_else(|| CommitAgreementError::NotSigned(id.clone()))?,
        };
        net::from(requestor_id)
            .to(provider_id)
            .service(&provider::agreement_addr(BUS_ID))
            .send(msg)
            .map_err(|e| GsbAgreementError(e.to_string(), id))
            .await??;
        Ok(())
    }

    /// Sent to provider, when Requestor will call cancel Agreement,
    /// while waiting for approval.
    pub async fn cancel_agreement(
        &self,
        agreement: &Agreement,
        reason: Option<Reason>,
        timestamp: NaiveDateTime,
    ) -> Result<(), AgreementProtocolError> {
        let msg = AgreementCancelled {
            agreement_id: agreement.id.clone(),
            reason,
            cancellation_ts: timestamp,
        };
        net::from(agreement.requestor_id)
            .to(agreement.provider_id)
            .service(&provider::agreement_addr(BUS_ID))
            .send(msg)
            .await
            .map_err(|e| GsbAgreementError(e.to_string(), agreement.id.clone()))??;
        Ok(())
    }

    async fn on_proposal_received(
        self,
        caller: String,
        msg: ProposalReceived,
    ) -> Result<(), CounterProposalError> {
        log::trace!(
            "Negotiation API: Received proposal [{}] from [{}].",
            &msg.proposal.proposal_id,
            &caller
        );
        self.inner
            .proposal_received
            .call(caller, msg.translate(Owner::Requestor))
            .await
    }

    async fn on_proposal_rejected(
        self,
        caller: String,
        msg: ProposalRejected,
    ) -> Result<(), RejectProposalError> {
        log::debug!(
            "Negotiation API: Proposal [{}] rejected by [{}].",
            &msg.proposal_id,
            &caller
        );
        self.inner
            .proposal_rejected
            .call(caller, msg.translate(Owner::Requestor))
            .await
    }

    async fn on_agreement_approved(
        self,
        caller: String,
        msg: AgreementApproved,
    ) -> Result<(), AgreementProtocolError> {
        log::debug!(
            "Negotiation API: Agreement [{}] approved by [{}].",
            &msg.agreement_id,
            &caller
        );
        self.inner
            .agreement_approved
            .call(caller, msg.translate(Owner::Requestor))
            .await
    }

    async fn on_agreement_rejected(
        self,
        caller: String,
        msg: AgreementRejected,
    ) -> Result<(), AgreementProtocolError> {
        log::debug!(
            "Negotiation API: Agreement [{}] rejected by [{}].",
            &msg.agreement_id,
            &caller
        );
        self.inner
            .agreement_rejected
            .call(caller, msg.translate(Owner::Requestor))
            .await
    }

    async fn on_agreement_terminated(
        self,
        caller: String,
        msg: AgreementTerminated,
    ) -> Result<(), TerminateAgreementError> {
        log::debug!(
            "Negotiation API: Agreement [{}] terminated by [{}].",
            &msg.agreement_id,
            &caller
        );
        self.inner
            .agreement_terminated
            .call(caller, msg.translate(Owner::Requestor))
            .await
    }

    pub async fn bind_gsb(
        &self,
        public_prefix: &str,
        _local_prefix: &str,
    ) -> Result<(), NegotiationApiInitError> {
        log::info!("Negotiation (Requestor) protocol version: mk1");

        ServiceBinder::new(&requestor::proposal_addr(public_prefix), &(), self.clone())
            .bind_with_processor(move |_, myself, caller: String, msg: ProposalReceived| {
                let myself = myself;
                myself.on_proposal_received(caller, msg)
            })
            .bind_with_processor(move |_, myself, caller: String, msg: ProposalRejected| {
                let myself = myself;
                myself.on_proposal_rejected(caller, msg)
            });

        ServiceBinder::new(&requestor::agreement_addr(public_prefix), &(), self.clone())
            .bind_with_processor(move |_, myself, caller: String, msg: AgreementApproved| {
                let myself = myself;
                myself.on_agreement_approved(caller, msg)
            })
            .bind_with_processor(move |_, myself, caller: String, msg: AgreementRejected| {
                let myself = myself;
                myself.on_agreement_rejected(caller, msg)
            })
            .bind_with_processor(move |_, myself, caller: String, msg: AgreementTerminated| {
                let myself = myself;
                myself.on_agreement_terminated(caller, msg)
            });
        Ok(())
    }
}
