name: Payment test

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Profile (unused right now)'
        required: true
        default: 'debug'

jobs:
  build:
    name: Payment test
    env:
      # `-D warnings` means any warnings emitted will cause build to fail
      RUSTFLAGS: "-C opt-level=z -C debuginfo=1"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install tools
        uses: ./.github/actions/setup-tools
        with:
          tools: rust protoc python

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: Install openssl ( Windows only )
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          vcpkg install openssl:x64-windows
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

          $opensslRoot = Join-Path $env:VCPKG_INSTALLATION_ROOT "installed\x64-windows"
          "OPENSSL_DIR=$opensslRoot" >> $env:GITHUB_ENV
          "OPENSSL_LIB_DIR=$(Join-Path $opensslRoot 'lib')" >> $env:GITHUB_ENV
          "OPENSSL_INCLUDE_DIR=$(Join-Path $opensslRoot 'include')" >> $env:GITHUB_ENV

      - name: Build
        run: |
          cargo build
          cargo build -p erc20_processor

      - name: Run test
        run: |
          cd extra/payments/multi_test
          python payment_test.py
